const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const listeners = {};
const fields = [{id:'ambiente',type:'select',value:'sandbox'}, {id:'client_id',type:'text',value:'masked'}];
const icon = {classList:{add(){},remove(){}}};
const button = {dataset:{description:'Ative na Cora',error:'Falha'},style:{},setAttribute(){},querySelector(){return icon;},addEventListener(event,fn){listeners[event]=fn;}};
const description = {textContent:'Configure no painel'};
const form = {querySelectorAll(){return fields;},addEventListener(event,fn){listeners['form:'+event]=fn;}};
const messages=[]; let requests=0; let finish;
const state = {code:'asaas',id:1,certificate:{},clientId:'masked'};
const context = {window:{parent:{postMessage(message){messages.push(message);}}},document:{getElementById(id){return {btnActivateCoraWebhook:button,formPrincipal:form,webhookDescription:description}[id];}},API:{post(){requests++;return new Promise(resolve=>{finish=resolve;});}}};
vm.createContext(context);
vm.runInContext(fs.readFileSync('public/assets/js/cora-webhook.min.js','utf8'),context);
const ui=context.window.CoraWebhookButton(()=>state);
(async()=>{
    ui.saved();assert.equal(button.hidden,true);
    state.code='cora';ui.sync();assert.equal(button.hidden,false);assert.equal(button.disabled,false);
    fields[1].value='unsaved';listeners['form:input']();assert.equal(button.disabled,true);
    fields[1].value='masked';ui.sync();assert.equal(button.disabled,false);
    state.certificate=null;ui.sync();assert.equal(button.disabled,true);
    state.certificate={};ui.sync();
    const running=listeners.click();assert.equal(button.disabled,true);
    await listeners.click();assert.equal(requests,1);
    finish({success:true,message:'Webhook ativado'});await running;
    assert.equal(messages[0].action,'openAlert');assert.equal(button.disabled,false);
    state.id=null;ui.sync();assert.equal(button.disabled,true);
    console.log('[OK] Botão Cora: visibilidade, alterações não salvas, certificado e clique duplicado.');
})().catch(error=>{console.error(error);process.exitCode=1;});
