// Requer jsdom no ambiente de testes; não adiciona dependência ao aplicativo.
const {JSDOM} = require('jsdom');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
const dom = new JSDOM(`<label for="diagram">Diagrama</label><select id="diagram" class="chosen-select" data-chosen-image-preview="true" data-chosen-allow-clear="false"><option value="sedan.jpg" data-preview-src="/sedan.jpg">Sedan</option><option value="suv.jpg" data-preview-src="/suv.jpg">SUV</option><option value="legacy">Indisponível</option></select><select id="normal" class="chosen-select"><option value="a">A</option><option value="b">B</option></select>`, {runScripts:'outside-only', pretendToBeVisual:true, url:'https://example.test'});
const w=dom.window;
let touch=false;
w.matchMedia=()=>({matches:touch});
w.HTMLElement.prototype.scrollIntoView=function(){};
w.eval(fs.readFileSync(path.join(__dirname,'../public/assets/js/chosen-select.js'),'utf8'));
w.initChosenSelects();
const select=w.document.getElementById('diagram'), c=select.chosenSelect;
Object.defineProperty(c.dropdown,'offsetHeight',{value:300});
c.open();
assert.equal(c.previewImage.alt,'Sedan');
const suv=c.optionsContainer.querySelector('[data-value="suv.jpg"]');
suv.dispatchEvent(new w.Event('pointerover',{bubbles:true}));
assert.equal(c.previewImage.alt,'SUV');
assert.equal(select.value,'sedan.jpg','Hover não deve salvar seleção');
c.previewImage.dispatchEvent(new w.Event('error'));
assert.equal(c.previewError.hidden,false);
c.filterOptions('suv'); c.highlightNext();
c.searchInput.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
assert.equal(select.value,'suv.jpg'); assert.equal(c.isOpen,false);
c.open(); c.showImagePreview('legacy'); assert.equal(c.previewError.hidden,false);
touch=true; c.filterOptions(''); c.optionsContainer.querySelector('[data-value="sedan.jpg"]').dispatchEvent(new w.MouseEvent('click',{bubbles:true})); assert.equal(c.isOpen,true); assert.equal(c.previewImage.alt,'Sedan');
Object.defineProperty(w,'innerWidth',{value:390,configurable:true});
Object.defineProperty(w,'innerHeight',{value:600,configurable:true});
c.positionImagePreview({left:350,right:390,width:40,bottom:570});
assert(c.dropdown.classList.contains('chosen-select-preview-compact'));
assert(parseFloat(c.dropdown.style.left)+parseFloat(c.dropdown.style.width)<=382);
assert(parseFloat(c.dropdown.style.top)+300<=592);
c.searchInput.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true})); assert.equal(c.isOpen,false);
c.open(); w.document.body.dispatchEvent(new w.MouseEvent('click',{bubbles:true})); assert.equal(c.isOpen,false);
const n=w.document.getElementById('normal').chosenSelect;
Object.defineProperty(n.dropdown,'offsetHeight',{value:100});
n.open(); n.highlightNext(); n.highlightNext();
n.searchInput.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));
assert.equal(n.select.value,'a'); assert.equal(n.preview,undefined);
n.close(); c.destroy(); dom.window.close();
console.log('OK: hover, busca, teclado, touch, posicionamento, falha de imagem e regressão do select comum.');
