<?php

/**
 * Maintenance module translations - English (US)
 *
 * Contains shared item labels between screens:
 * - Maintenance Plans (CRUD)
 * - Maintenance (Work Orders)
 * - Verification CRON
 */

return [
    // General titles
    'title' => 'Maintenance',
    'preventive_title' => 'Preventive Maintenance',

    // Maintenance item labels (shared)
    'items' => [
        'motor_oleo' => 'Engine oil',
        'motor_filtrooleo' => 'Oil filter',
        'motor_correiadentada' => 'Timing belt',
        'motor_correiaalternador' => 'Alternator belt',
        'motor_correiaarcondicionado' => 'A/C belt',
        'motor_correiabombadagua' => 'Water pump belt',
        'motor_filtrodear' => 'Engine air filter',
        'motor_filtrodecabine' => 'Cabin air filter',
        'motor_filtrodecombustivel' => 'Fuel filter',
        'motor_fluidodofreio' => 'Brake fluid',
        'motor_fluidoembreagem' => 'Clutch fluid',
        'motor_discodeembreagem' => 'Clutch disc',
        'motor_fluidocaixademarcha' => 'Transmission fluid',
        'motor_limpesaarrefecimento' => 'Cooling system flush',
        'motor_vejas' => 'Spark plugs',
        'motor_bateria' => 'Battery',
        'rodagem_pneus' => 'Tires',
        'rodagem_alinhamento' => 'Wheel alignment',
        'rodagem_pastilhasdefreio' => 'Brake pads',
        'rodagem_discodefreios' => 'Brake discs',
        'rodagem_rodiziodepneus' => 'Tire rotation',
        'acessorio_paletasparabrisa' => 'Wiper blades',
        'moto_corrente' => 'Drive chain',
        'moto_kitrelacao' => 'Sprocket kit',
        'moto_oleosuspensao' => 'Fork/suspension oil',
        'moto_caboembreagem' => 'Clutch cable',
        'moto_caboacelerador' => 'Throttle cable',
    ],

    // Categories (UI grouping)
    'categories' => [
        'motor' => 'Engine',
        'rodagem' => 'Drivetrain',
        'acessorio' => 'Accessories',
        'moto' => 'Motorcycle',
    ],

    // CRON messages
    'cron' => [
        'disabled' => 'Preventive maintenance disabled via ENV',
        'processing_tenant' => 'Processing tenant: :chave',
        'os_generated' => 'WO :codigo generated for vehicle :placa',
        'finished' => 'Finished: :tenants tenants | :veiculos vehicles | :os WOs generated',
        'result' => 'Processed :tenants tenants, :veiculos vehicles, :os WOs generated',
    ],

    // Audit logs
    'audit' => [
        'os_created' => 'System generated preventive maintenance for vehicle [:placa] - WO [:codigo]',
    ],

    // Generated WO fields
    'os' => [
        'reason' => 'Preventive maintenance generated by system.',
        'status_created' => 'Created by system',
    ],

    // Notifications (per vehicle - detailed)
    'notifications' => [
        'email_subject' => 'Preventive Maintenance - Plate :placa',
        'email_body' => "Vehicle: :placa\nCurrent Odometer: :odometro km\n\nMaintenance items due:\n:itens\n\nA Work Order was automatically created.",
        'whatsapp_title' => '*Preventive Maintenance*',
        'whatsapp_body' => "Vehicle: :placa\nItems: :itens\n\nWO automatically created in the system.",
    ],

    // CRON notifications (consolidated per tenant)
    'cron_notifications' => [
        'email_subject' => 'Preventive Maintenance Created',
        'email_body' => 'Preventive maintenance has been created, access the vehicles > maintenance menu.',
        'sms_body' => 'Preventive maintenance has been created, access the vehicles > maintenance menu.',
        'whatsapp_body' => '*[7Carros]* Preventive maintenance has been created, access the vehicles > maintenance menu.',
    ],

    // ===== Views (index.php + adicionar.php) =====

    // View titles
    'title_list' => 'Maintenance',
    'new_title' => 'New Maintenance',
    'edit_title' => 'Edit Maintenance',

    // Tabs
    'tabs' => [
        'data' => 'Data',
        'items' => 'Items',
        'financial' => 'Financial',
    ],

    // Sections
    'sections' => [
        'maintenance_data' => 'Maintenance Data',
        'send_to_workshop' => 'Send to workshop',
        'return_from_workshop' => 'Return from workshop',
        'services_performed' => 'Services Performed',
        'services_performed_note' => 'This information is only for record keeping and may be used in future calculations.',
        'maintenance_items' => 'Maintenance Items',
        'financial_entries' => 'Financial Entries',
        'entry_config' => 'Entry Configuration',
    ],

    // Fields
    'fields' => [
        'os' => 'WO',
        'status' => 'Status',
        'branch' => 'Parent/Branch',
        'vehicle' => 'Vehicle',
        'workshop' => 'Workshop',
        'send_date' => 'Send Date',
        'send_odometer' => 'Send Odometer',
        'send_tank' => 'Send Tank',
        'return_date' => 'Return Date',
        'return_odometer' => 'Return Odometer',
        'return_tank' => 'Return Tank',
        'odometer' => 'Odometer',
        'tank' => 'Tank',
        'send_reason' => 'Reason for sending to workshop',
        'workshop_notes' => 'Workshop Notes',
        'changed_oil' => 'Changed Oil',
        'changed_tires' => 'Changed Tires',
        'product' => 'Product',
        'qty' => 'Qty',
        'unit_value' => 'Unit Value',
        'total_value' => 'Total Value',
        'action' => 'Action',
        'description' => 'Description',
        'value' => 'Value',
        'payment_method' => 'Payment Method',
        'installments' => 'Installments',
        'first_due_date' => '1st Due Date',
        'interval_days' => 'Interval (days)',
    ],

    // Status options
    'status_options' => [
        'created' => 'Created',
        'created_by_system' => 'Created by system',
        'open' => 'Open',
        'closed' => 'Closed',
    ],

    // Tank levels
    'tank_levels' => [
        'full' => 'Full',
        'reserve' => 'Reserve',
    ],

    // Badges
    'badges' => [
        'paid' => 'Paid',
        'pending' => 'Pending',
        'new' => 'New',
        'editing' => 'Editing',
    ],

    // Actions
    'actions' => [
        'new' => 'New',
        'add_item' => 'Add Item',
        'create_full_entry' => 'Create Full Entry',
        'close_selected' => 'Close Selected Items',
        'go_to_list' => 'Go to List',
    ],

    // Table
    'table' => [
        'os' => 'WO',
        'vehicle' => 'Vehicle',
        'workshop' => 'Workshop',
        'send_date' => 'Send Date',
        'total' => 'Total',
        'status' => 'Status',
        'actions' => 'Actions',
        'totals' => 'Totals:',
        'total_paid' => 'Total Paid:',
        'total_pending' => 'Total Pending:',
        'total_selected' => 'Total Selected:',
    ],

    // Placeholders
    'placeholders' => [
        'search' => 'Search WO, vehicle...',
        'select' => 'Select...',
        'search_type' => 'Type to search...',
        'search_product' => 'Search product...',
        'search_product_service' => 'Search product/service...',
        'item_description' => 'Item description',
        'manual_description' => 'Type description manually',
    ],

    // Messages
    'messages' => [
        'no_records' => 'No maintenance records found',
        'load_error' => 'Error loading',
        'server_error' => 'Connection error',
        'delete_error' => 'Error deleting',
        'save_error' => 'Error saving',
        'save_success' => 'Maintenance saved successfully',
        'no_items' => 'No items added',
        'no_pending_items' => 'No pending items',
        'select_product' => 'Select a product',
        'cannot_remove_paid' => 'Cannot remove paid items',
        'cannot_edit_paid' => 'Cannot edit paid items',
        'provide_description' => 'Provide a description or select a product',
        'product_out_of_stock' => 'Product out of stock.',
        'stock_insufficient' => 'Only :qty available. Quantity adjusted.',
        'select_at_least_one' => 'Select at least one item',
        'entry_created' => 'Entry created successfully',
        'generic_error' => 'Error',
        'odometer_required' => 'Enter the return odometer',
        'saved_title' => 'Maintenance Saved',
        'saved_go_to_list' => 'Go back to the list?',
        'financial_desc' => 'Select pending items to create a partial financial entry or click "Create Full Entry" to include all.',
    ],

    // Pagination
    'pagination' => [
        'rows_per_page' => 'Rows per page:',
        'showing' => 'Showing :start-:end of :total records',
        'page_navigation' => 'Page navigation',
    ],

    // Print
    'print' => [
        'title' => 'Work Order',
        'action' => 'Print',
        'cpf_cnpj_label' => 'CPF/CNPJ:',
    ],

    // Record type (for delete modal)
    'record_type' => 'manutencao',

    // Financial audit
    'audit_financial' => [
        'section' => 'Financial Entry',
        'type' => 'Type',
        'complete' => 'Complete',
        'partial' => 'Partial',
        'payment_method' => 'Payment Method',
        'installments' => 'Installments',
        'first_due_date' => '1st Due Date',
        'interval' => 'Interval',
        'days' => 'days',
        'total_value' => 'Total Value',
        'selected_items' => 'Selected Items',
        'item' => 'Item',
        'value' => 'Value',
    ],
];
