#!/usr/bin/env python3
"""Acentua valores (lado direito de =>) em app/lang/pt_BR ou pt_PT/**/*.php"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
_DEFAULT_LANG = "pt_BR"


def lang_dir_for(code: str) -> Path:
    return ROOT / "app" / "lang" / code


def extract_string_span(line: str) -> tuple[int, int] | None:
    if "=>" not in line:
        return None
    arrow = line.index("=>")
    rest = line[arrow + 2 :]
    m = re.match(r"\s*(['\"])", rest)
    if not m:
        return None
    q = m.group(1)
    i = m.end()
    escaped = False
    while i < len(rest):
        c = rest[i]
        if escaped:
            escaped = False
            i += 1
            continue
        if c == "\\":
            escaped = True
            i += 1
            continue
        if c == q:
            inner_start = arrow + 2 + m.end()
            inner_end = arrow + 2 + i
            return (inner_start, inner_end)
        i += 1
    return None


def _pt_pt_postprocess(s: str) -> str:
    """Ajusta grafias preferidas em pt_PT (vs pt_BR) após as regras comuns."""
    pairs = [
        ("econômicas", "económicas"),
        ("Econômicas", "Económicas"),
        ("econômicos", "económicos"),
        ("Econômicos", "Económicos"),
        ("econômica", "económica"),
        ("Econômica", "Económica"),
        ("econômico", "económico"),
        ("Econômico", "Económico"),
        ("atômicas", "atómicas"),
        ("Atômicas", "Atómicas"),
        ("atômicos", "atómicos"),
        ("Atômicos", "Atómicos"),
        ("atômica", "atómica"),
        ("Atômica", "Atómica"),
        ("atômico", "atómico"),
        ("Atômico", "Atómico"),
        ("anônimos", "anónimos"),
        ("Anônimos", "Anónimos"),
        ("anônimas", "anónimas"),
        ("Anônimas", "Anónimas"),
        ("anônima", "anónima"),
        ("Anônima", "Anónima"),
        ("anônimo", "anónimo"),
        ("Anônimo", "Anónimo"),
    ]
    for a, b in pairs:
        s = s.replace(a, b)
    return s


def transform_value(s: str, locale: str = "pt_BR") -> str:
    rules: list[tuple[str, str]] = [
        (r"\bNao e possivel\b", "Não é possível"),
        (r"\bnao e possivel\b", "não é possível"),
        (r"\bNao e equivalente\b", "Não é equivalente"),
        (r"\bnao e equivalente\b", "não é equivalente"),
        (r"\bNao e\b", "Não é"),
        (r"\bnao e\b", "não é"),
        (r"\bNao ha\b", "Não há"),
        (r"\bnao ha\b", "não há"),
        (r"\bNao foi possivel\b", "Não foi possível"),
        (r"\bnao foi possivel\b", "não foi possível"),
        (r"\bNao foi\b", "Não foi"),
        (r"\bnao foi\b", "não foi"),
        (r"\bNao pode ser\b", "Não pode ser"),
        (r"\bnao pode ser\b", "não pode ser"),
        (r"\bNao pode\b", "Não pode"),
        (r"\bnao pode\b", "não pode"),
        (r"\bNao podem\b", "Não podem"),
        (r"\bnao podem\b", "não podem"),
        (r"\bNao tem\b", "Não tem"),
        (r"\bnao tem\b", "não tem"),
        (r"\bNao esta\b", "Não está"),
        (r"\bnao esta\b", "não está"),
        (r"\bNao estao\b", "Não estão"),
        (r"\bnao estao\b", "não estão"),
        (r"\bNao confere\b", "Não confere"),
        (r"\bnao confere\b", "não confere"),
        (r"\bNao Pago\b", "Não Pago"),
        (r"\bNao pago\b", "Não pago"),
        (r"\bnao pago\b", "não pago"),
        (r"\bNao processadas\b", "Não processadas"),
        (r"\bnao processadas\b", "não processadas"),
        (r"\bNao processado\b", "Não processado"),
        (r"\bnao processado\b", "não processado"),
        (r"\bNao encontrada\b", "Não encontrada"),
        (r"\bnao encontrada\b", "não encontrada"),
        (r"\bNao encontrado\b", "Não encontrado"),
        (r"\bnao encontrado\b", "não encontrado"),
        (r"\bNao encontradas\b", "Não encontradas"),
        (r"\bnao encontradas\b", "não encontradas"),
        (r"\bNao encontrados\b", "Não encontrados"),
        (r"\bnao encontrados\b", "não encontrados"),
        (r"\bNao disponivel\b", "Não disponível"),
        (r"\bnao disponivel\b", "não disponível"),
        (r"\bNao adicionou\b", "Não adicionou"),
        (r"\bnao adicionou\b", "não adicionou"),
        (r"\bNao equivalente\b", "Não equivalente"),
        (r"\bnao equivalente\b", "não equivalente"),
        (r"\bNao corresponde\b", "Não corresponde"),
        (r"\bnao corresponde\b", "não corresponde"),
        (r"\bNao reconhecido\b", "Não reconhecido"),
        (r"\bnao reconhecido\b", "não reconhecido"),
        (r"\bNao reconhecida\b", "Não reconhecida"),
        (r"\bnao reconhecida\b", "não reconhecida"),
        (r"\bnao ser\b", "não ser"),
        (r"\bNao ser\b", "Não ser"),
        (r"\bnao tenha\b", "não tenha"),
        (r"\bNao tenha\b", "Não tenha"),
        (r"\bnao tenham\b", "não tenham"),
        (r"\bNao tenham\b", "Não tenham"),
        (r"\bnao tiver\b", "não tiver"),
        (r"\bNao tiver\b", "Não tiver"),
        (r"\bnao tinha\b", "não tinha"),
        (r"\bNao tinha\b", "Não tinha"),
        (r"\bnao tinham\b", "não tinham"),
        (r"\bNao tinham\b", "Não tinham"),
        (r"\bnao sera\b", "não será"),
        (r"\bNao sera\b", "Não será"),
        (r"\bnao sao\b", "não são"),
        (r"\bNao sao\b", "Não são"),
        (r"\bnao se\b", "não se"),
        (r"\bNao se\b", "Não se"),
        (r"\bnao foram\b", "não foram"),
        (r"\bNao foram\b", "Não foram"),
        (r"\bnao existe\b", "não existe"),
        (r"\bNao existe\b", "Não existe"),
        (r"\bnao existem\b", "não existem"),
        (r"\bNao existem\b", "Não existem"),
        (r"\bnao havera\b", "não haverá"),
        (r"\bNao havera\b", "Não haverá"),
        (r"\bVoce\b", "Você"),
        (r"\bvoce\b", "você"),
        (r"\bVoces\b", "Vocês"),
        (r"\bvoces\b", "vocês"),
        (r"\bTambem\b", "Também"),
        (r"\btambem\b", "também"),
        (r"\bAlem\b", "Além"),
        (r"\balem\b", "além"),
        (r"\bAte\b", "Até"),
        (r"\bate\b", "até"),
        (r"\bApos\b", "Após"),
        (r"\bapos\b", "após"),
        (r"\bPorem\b", "Porém"),
        (r"\bporem\b", "porém"),
        (r"\bJa\b", "Já"),
        (r"\bja\b", "já"),
        (r"\bHa\b", "Há"),
        (r"\bha\b", "há"),
        (r"\bSera\b", "Será"),
        (r"\bsera\b", "será"),
        (r"\bIra\b", "Irá"),
        (r"\bira\b", "irá"),
        (r"\bserao\b", "serão"),
        (r"\bSerao\b", "Serão"),
        (r"\bestao\b", "estão"),
        (r"\bEstao\b", "Estão"),
        (r"\bUsuario\b", "Usuário"),
        (r"\busuario\b", "usuário"),
        (r"\bUsuarios\b", "Usuários"),
        (r"\busuarios\b", "usuários"),
        (r"\binvalidas\b", "inválidas"),
        (r"\bInvalidas\b", "Inválidas"),
        (r"\binvalida\b", "inválida"),
        (r"\bInvalida\b", "Inválida"),
        (r"\binvalidos\b", "inválidos"),
        (r"\bInvalidos\b", "Inválidos"),
        (r"\binvalido\b", "inválido"),
        (r"\bInvalido\b", "Inválido"),
        (r"\bAgencia\b", "Agência"),
        (r"\bagencia\b", "agência"),
        (r"\bFuncoes\b", "Funções"),
        (r"\bfuncoes\b", "funções"),
        (r"\bFuncao\b", "Função"),
        (r"\bfuncao\b", "função"),
        (r"\bCartoes\b", "Cartões"),
        (r"\bcartoes\b", "cartões"),
        (r"\bCartao\b", "Cartão"),
        (r"\bcartao\b", "cartão"),
        (r"\bNumero\b", "Número"),
        (r"\bnumero\b", "número"),
        (r"\bCodigo\b", "Código"),
        (r"\bcodigo\b", "código"),
        (r"\bCodigos\b", "Códigos"),
        (r"\bcodigos\b", "códigos"),
        (r"\bVeiculo\b", "Veículo"),
        (r"\bveiculo\b", "veículo"),
        (r"\bVeiculos\b", "Veículos"),
        (r"\bveiculos\b", "veículos"),
        (r"\bHistorico\b", "Histórico"),
        (r"\bhistorico\b", "histórico"),
        (r"\bOcorrencia\b", "Ocorrência"),
        (r"\bocorrencia\b", "ocorrência"),
        (r"\bOcorrencias\b", "Ocorrências"),
        (r"\bocorrencias\b", "ocorrências"),
        (r"\bEconomico\b", "Econômico"),
        (r"\beconomico\b", "econômico"),
        (r"\bEconomica\b", "Econômica"),
        (r"\beconomica\b", "econômica"),
        (r"\bEletrico\b", "Elétrico"),
        (r"\beletrico\b", "elétrico"),
        (r"\bEletrica\b", "Elétrica"),
        (r"\beletrica\b", "elétrica"),
        (r"\bLogico\b", "Lógico"),
        (r"\blogico\b", "lógico"),
        (r"\bLogica\b", "Lógica"),
        (r"\blogica\b", "lógica"),
        (r"\bPratico\b", "Prático"),
        (r"\bpratico\b", "prático"),
        (r"\bPratica\b", "Prática"),
        (r"\bpratica\b", "prática"),
        (r"\bTeorico\b", "Teórico"),
        (r"\bteorico\b", "teórico"),
        (r"\bTeorica\b", "Teórica"),
        (r"\bteorica\b", "teórica"),
        (r"\bCritico\b", "Crítico"),
        (r"\bcritico\b", "crítico"),
        (r"\bCritica\b", "Crítica"),
        (r"\bcritica\b", "crítica"),
        (r"\bClinico\b", "Clínico"),
        (r"\bclinico\b", "clínico"),
        (r"\bClinica\b", "Clínica"),
        (r"\bclinica\b", "clínica"),
        (r"\bMetrica\b", "Métrica"),
        (r"\bmetrica\b", "métrica"),
        (r"\bMetricas\b", "Métricas"),
        (r"\bmetricas\b", "métricas"),
        (r"\bDinamico\b", "Dinâmico"),
        (r"\bdinamico\b", "dinâmico"),
        (r"\bDinamica\b", "Dinâmica"),
        (r"\bdinamica\b", "dinâmica"),
        (r"\bCiclico\b", "Cíclico"),
        (r"\bciclico\b", "cíclico"),
        (r"\bCiclica\b", "Cíclica"),
        (r"\bciclica\b", "cíclica"),
        (r"\bPublico\b", "Público"),
        (r"\bpublico\b", "público"),
        (r"\bPublica\b", "Pública"),
        (r"\bpublica\b", "pública"),
        (r"\bVinculo\b", "Vínculo"),
        (r"\bvinculo\b", "vínculo"),
        (r"\bVinculos\b", "Vínculos"),
        (r"\bvinculos\b", "vínculos"),
        (r"\bSubtitulo\b", "Subtítulo"),
        (r"\bsubtitulo\b", "subtítulo"),
        (r"\bCapitulo\b", "Capítulo"),
        (r"\bcapitulo\b", "capítulo"),
        (r"\bCapitulos\b", "Capítulos"),
        (r"\bcapitulos\b", "capítulos"),
        (r"\bRodape\b", "Rodapé"),
        (r"\brodape\b", "rodapé"),
        (r"\bReferencias\b", "Referências"),
        (r"\breferencias\b", "referências"),
        (r"\bReferencia\b", "Referência"),
        (r"\breferencia\b", "referência"),
        (r"\bPreferencias\b", "Preferências"),
        (r"\bpreferencias\b", "preferências"),
        (r"\bPreferencia\b", "Preferência"),
        (r"\bpreferencia\b", "preferência"),
        (r"\bExperiencias\b", "Experiências"),
        (r"\bexperiencias\b", "experiências"),
        (r"\bExperiencia\b", "Experiência"),
        (r"\bexperiencia\b", "experiência"),
        (r"\bSequencias\b", "Sequências"),
        (r"\bsequencias\b", "sequências"),
        (r"\bSequencia\b", "Sequência"),
        (r"\bsequencia\b", "sequência"),
        (r"\bFrequencias\b", "Frequências"),
        (r"\bfrequencias\b", "frequências"),
        (r"\bFrequencia\b", "Frequência"),
        (r"\bfrequencia\b", "frequência"),
        (r"\bConsequencias\b", "Consequências"),
        (r"\bconsequencias\b", "consequências"),
        (r"\bConsequencia\b", "Consequência"),
        (r"\bconsequencia\b", "consequência"),
        (r"\bLicenca\b", "Licença"),
        (r"\blicenca\b", "licença"),
        (r"\bLicencas\b", "Licenças"),
        (r"\blicencas\b", "licenças"),
        (r"\bTendencias\b", "Tendências"),
        (r"\btendencias\b", "tendências"),
        (r"\bTendencia\b", "Tendência"),
        (r"\btendencia\b", "tendência"),
        (r"\bDependencias\b", "Dependências"),
        (r"\bdependencias\b", "dependências"),
        (r"\bDependencia\b", "Dependência"),
        (r"\bdependencia\b", "dependência"),
        (r"\bIndependencia\b", "Independência"),
        (r"\bindependencia\b", "independência"),
        (r"\bEmergencias\b", "Emergências"),
        (r"\bemergencias\b", "emergências"),
        (r"\bEmergencia\b", "Emergência"),
        (r"\bemergencia\b", "emergência"),
        (r"\bUrgencias\b", "Urgências"),
        (r"\burgencias\b", "urgências"),
        (r"\bUrgencia\b", "Urgência"),
        (r"\burgencia\b", "urgência"),
        (r"\bEficiencias\b", "Eficiências"),
        (r"\beficiencias\b", "eficiências"),
        (r"\bEficiencia\b", "Eficiência"),
        (r"\beficiencia\b", "eficiência"),
        (r"\bCiencias\b", "Ciências"),
        (r"\bciencias\b", "ciências"),
        (r"\bCiencia\b", "Ciência"),
        (r"\bciencia\b", "ciência"),
        (r"\bAudiencias\b", "Audiências"),
        (r"\baudiencias\b", "audiências"),
        (r"\bAudiencia\b", "Audiência"),
        (r"\baudiencia\b", "audiência"),
        (r"\bConsciencia\b", "Consciência"),
        (r"\bconsciencia\b", "consciência"),
        (r"\bInconsciencia\b", "Inconsciência"),
        (r"\binconsciencia\b", "inconsciência"),
        (r"\bEssencias\b", "Essências"),
        (r"\bessencias\b", "essências"),
        (r"\bEssencia\b", "Essência"),
        (r"\bessencia\b", "essência"),
        (r"\bDecadencia\b", "Decadência"),
        (r"\bdecadencia\b", "decadência"),
        (r"\bVigencias\b", "Vigências"),
        (r"\bvigencias\b", "vigências"),
        (r"\bVigencia\b", "Vigência"),
        (r"\bvigencia\b", "vigência"),
        (r"\bRegencias\b", "Regências"),
        (r"\bregencias\b", "regências"),
        (r"\bRegencia\b", "Regência"),
        (r"\bregencia\b", "regência"),
        (r"\bPotencias\b", "Potências"),
        (r"\bpotencias\b", "potências"),
        (r"\bPotencia\b", "Potência"),
        (r"\bpotencia\b", "potência"),
        (r"\bCompetencias\b", "Competências"),
        (r"\bcompetencias\b", "competências"),
        (r"\bCompetencia\b", "Competência"),
        (r"\bcompetencia\b", "competência"),
        (r"\bIncompetencia\b", "Incompetência"),
        (r"\bincompetencia\b", "incompetência"),
        (r"\bTransparencias\b", "Transparências"),
        (r"\btransparencias\b", "transparências"),
        (r"\bTransparencia\b", "Transparência"),
        (r"\btransparencia\b", "transparência"),
        (r"\bDiferencas\b", "Diferenças"),
        (r"\bdiferencas\b", "diferenças"),
        (r"\bDiferenca\b", "Diferença"),
        (r"\bdiferenca\b", "diferença"),
        (r"\bRelevancias\b", "Relevâncias"),
        (r"\brelevancias\b", "relevâncias"),
        (r"\bRelevancia\b", "Relevância"),
        (r"\brelevancia\b", "relevância"),
        (r"\bImportancias\b", "Importâncias"),
        (r"\bimportancias\b", "importâncias"),
        (r"\bImportancia\b", "Importância"),
        (r"\bimportancia\b", "importância"),
        (r"\bDistancias\b", "Distâncias"),
        (r"\bdistancias\b", "distâncias"),
        (r"\bDistancia\b", "Distância"),
        (r"\bdistancia\b", "distância"),
        (r"\bInstancias\b", "Instâncias"),
        (r"\binstancias\b", "instâncias"),
        (r"\bInstancia\b", "Instância"),
        (r"\binstancia\b", "instância"),
        (r"\bCircunstancias\b", "Circunstâncias"),
        (r"\bcircunstancias\b", "circunstâncias"),
        (r"\bCircunstancia\b", "Circunstância"),
        (r"\bcircunstancia\b", "circunstância"),
        (r"\bSubstancias\b", "Substâncias"),
        (r"\bsubstancias\b", "substâncias"),
        (r"\bSubstancia\b", "Substância"),
        (r"\bsubstancia\b", "substância"),
        (r"\bAssistencias\b", "Assistências"),
        (r"\bassistencias\b", "assistências"),
        (r"\bAssistencia\b", "Assistência"),
        (r"\bassistencia\b", "assistência"),
        (r"\bResistencias\b", "Resistências"),
        (r"\bresistencias\b", "resistências"),
        (r"\bResistencia\b", "Resistência"),
        (r"\bresistencia\b", "resistência"),
        (r"\bPersistencia\b", "Persistência"),
        (r"\bpersistencia\b", "persistência"),
        (r"\bInsistencia\b", "Insistência"),
        (r"\binsistencia\b", "insistência"),
        (r"\bExistencias\b", "Existências"),
        (r"\bexistencias\b", "existências"),
        (r"\bExistencia\b", "Existência"),
        (r"\bexistencia\b", "existência"),
        (r"\bCoexistencia\b", "Coexistência"),
        (r"\bcoexistencia\b", "coexistência"),
        (r"\bInexistencia\b", "Inexistência"),
        (r"\binexistencia\b", "inexistência"),
        (r"\bSubsistencia\b", "Subsistência"),
        (r"\bsubsistencia\b", "subsistência"),
        (r"\bConsistencia\b", "Consistência"),
        (r"\bconsistencia\b", "consistência"),
        (r"\bInconsistencia\b", "Inconsistência"),
        (r"\binconsistencia\b", "inconsistência"),
        (r"\bPreexistencia\b", "Preexistência"),
        (r"\bpreexistencia\b", "preexistência"),
        (r"\bConferencias\b", "Conferências"),
        (r"\bconferencias\b", "conferências"),
        (r"\bConferencia\b", "Conferência"),
        (r"\bconferencia\b", "conferência"),
        (r"\bInadimplencia\b", "Inadimplência"),
        (r"\binadimplencia\b", "inadimplência"),
        (r"\bInadimplencias\b", "Inadimplências"),
        (r"\binadimplencias\b", "inadimplências"),
        (r"\bAntecedencia\b", "Antecedência"),
        (r"\bantecedencia\b", "antecedência"),
        (r"\bTransferencia\b", "Transferência"),
        (r"\btransferencia\b", "transferência"),
        (r"\barea\b", "área"),
        (r"\bArea\b", "Área"),
        (r"\bgrafico\b", "gráfico"),
        (r"\bGrafico\b", "Gráfico"),
        (r"\bgraficos\b", "gráficos"),
        (r"\bGraficos\b", "Gráficos"),
        (r"\bmedio\b", "médio"),
        (r"\bMedio\b", "Médio"),
        (r"\bmedia\b", "média"),
        (r"\bMedia\b", "Média"),
        (r"\btermica\b", "térmica"),
        (r"\bTermica\b", "Térmica"),
        (r"\btermico\b", "térmico"),
        (r"\bTermico\b", "Térmico"),
        (r"\batomica\b", "atômica"),
        (r"\bAtomica\b", "Atômica"),
        (r"\batomico\b", "atômico"),
        (r"\bAtomico\b", "Atômico"),
        (r"\bunico\b", "único"),
        (r"\bUnico\b", "Único"),
        (r"\bunica\b", "única"),
        (r"\bUnica\b", "Única"),
        (r"\bunicos\b", "únicos"),
        (r"\bUnicos\b", "Únicos"),
        (r"\bunicas\b", "únicas"),
        (r"\bUnicas\b", "Únicas"),
        (r"\bultimo\b", "último"),
        (r"\bUltimo\b", "Último"),
        (r"\bultima\b", "última"),
        (r"\bUltima\b", "Última"),
        (r"\bproximo\b", "próximo"),
        (r"\bProximo\b", "Próximo"),
        (r"\bproxima\b", "próxima"),
        (r"\bProxima\b", "Próxima"),
        (r"\bbasico\b", "básico"),
        (r"\bBasico\b", "Básico"),
        (r"\bbasica\b", "básica"),
        (r"\bBasica\b", "Básica"),
        (r"\btecnico\b", "técnico"),
        (r"\bTecnico\b", "Técnico"),
        (r"\btecnica\b", "técnica"),
        (r"\bTecnica\b", "Técnica"),
        (r"\bautomatico\b", "automático"),
        (r"\bAutomatico\b", "Automático"),
        (r"\bautomatica\b", "automática"),
        (r"\bAutomatica\b", "Automática"),
        (r"\brapido\b", "rápido"),
        (r"\bRapido\b", "Rápido"),
        (r"\brapida\b", "rápida"),
        (r"\bRapida\b", "Rápida"),
        (r"\bsalario\b", "salário"),
        (r"\bSalario\b", "Salário"),
        (r"\bhorario\b", "horário"),
        (r"\bHorario\b", "Horário"),
        (r"\bdiario\b", "diário"),
        (r"\bDiario\b", "Diário"),
        (r"\bpagina\b", "página"),
        (r"\bPagina\b", "Página"),
        (r"\bpaginas\b", "páginas"),
        (r"\bPaginas\b", "Páginas"),
        (r"\bmaximo\b", "máximo"),
        (r"\bMaximo\b", "Máximo"),
        (r"\bmaxima\b", "máxima"),
        (r"\bMaxima\b", "Máxima"),
        (r"\bminimo\b", "mínimo"),
        (r"\bMinimo\b", "Mínimo"),
        (r"\bminima\b", "mínima"),
        (r"\bMinima\b", "Mínima"),
        (r"\bobrigatorio\b", "obrigatório"),
        (r"\bObrigatorio\b", "Obrigatório"),
        (r"\bobrigatoria\b", "obrigatória"),
        (r"\bObrigatoria\b", "Obrigatória"),
        (r"\bobrigatorios\b", "obrigatórios"),
        (r"\bObrigatorios\b", "Obrigatórios"),
        (r"\bobrigatorias\b", "obrigatórias"),
        (r"\bObrigatorias\b", "Obrigatórias"),
        (r"\bResponsavel\b", "Responsável"),
        (r"\bresponsavel\b", "responsável"),
        (r"\bResponsaveis\b", "Responsáveis"),
        (r"\bresponsaveis\b", "responsáveis"),
        (r"\bMatricula\b", "Matrícula"),
        (r"\bmatricula\b", "matrícula"),
        (r"\bMatriculas\b", "Matrículas"),
        (r"\bmatriculas\b", "matrículas"),
        (r"\bmetodo\b", "método"),
        (r"\bMetodo\b", "Método"),
        (r"\btitulo\b", "título"),
        (r"\bTitulo\b", "Título"),
        (r"\bsimbolo\b", "símbolo"),
        (r"\bSimbolo\b", "Símbolo"),
        (r"\bpolitica\b", "política"),
        (r"\bPolitica\b", "Política"),
        (r"\bdisponivel\b", "disponível"),
        (r"\bDisponivel\b", "Disponível"),
        (r"\bindisponivel\b", "indisponível"),
        (r"\bIndisponivel\b", "Indisponível"),
        (r"\bdisponiveis\b", "disponíveis"),
        (r"\bDisponiveis\b", "Disponíveis"),
        (r"\bpossivel\b", "possível"),
        (r"\bPossivel\b", "Possível"),
        (r"\bimpossivel\b", "impossível"),
        (r"\bImpossivel\b", "Impossível"),
        (r"\banalise\b", "análise"),
        (r"\bAnalise\b", "Análise"),
        (r"\bsintese\b", "síntese"),
        (r"\bSintese\b", "Síntese"),
        (r"\bgenerico\b", "genérico"),
        (r"\bGenerico\b", "Genérico"),
        (r"\bgenerica\b", "genérica"),
        (r"\bGenerica\b", "Genérica"),
        (r"\bexcluido\b", "excluído"),
        (r"\bExcluido\b", "Excluído"),
        (r"\bexcluida\b", "excluída"),
        (r"\bExcluida\b", "Excluída"),
        (r"\bincluido\b", "incluído"),
        (r"\bIncluido\b", "Incluído"),
        (r"\bincluida\b", "incluída"),
        (r"\bIncluida\b", "Incluída"),
        (r"\bpadrao\b", "padrão"),
        (r"\bPadrao\b", "Padrão"),
        (r"\bbotao\b", "botão"),
        (r"\bBotao\b", "Botão"),
        (r"\bbotoes\b", "botões"),
        (r"\bBotoes\b", "Botões"),
        (r"\bfacil\b", "fácil"),
        (r"\bFacil\b", "Fácil"),
        (r"\bdificil\b", "difícil"),
        (r"\bDificil\b", "Difícil"),
        (r"\bpaginacao\b", "paginação"),
        (r"\bPaginacao\b", "Paginação"),
        (r"\bselecao\b", "seleção"),
        (r"\bSelecao\b", "Seleção"),
        (r"\bselecoes\b", "seleções"),
        (r"\bSelecoes\b", "Seleções"),
        (r"\bimpressao\b", "impressão"),
        (r"\bImpressao\b", "Impressão"),
        (r"\bimpressoes\b", "impressões"),
        (r"\bImpressoes\b", "Impressões"),
        (r"\bconexao\b", "conexão"),
        (r"\bConexao\b", "Conexão"),
        (r"\bconexoes\b", "conexões"),
        (r"\bConexoes\b", "Conexões"),
        (r"\bversao\b", "versão"),
        (r"\bVersao\b", "Versão"),
        (r"\bversoes\b", "versões"),
        (r"\bVersoes\b", "Versões"),
        (r"\bcredito\b", "crédito"),
        (r"\bCredito\b", "Crédito"),
        (r"\bcreditos\b", "créditos"),
        (r"\bCreditos\b", "Créditos"),
        (r"\bdebito\b", "débito"),
        (r"\bDebito\b", "Débito"),
        (r"\bdebitos\b", "débitos"),
        (r"\bDebitos\b", "Débitos"),
        (r"\bcalculo\b", "cálculo"),
        (r"\bCalculo\b", "Cálculo"),
        (r"\bcalculos\b", "cálculos"),
        (r"\bCalculos\b", "Cálculos"),
        (r"\bperiodo\b", "período"),
        (r"\bPeriodo\b", "Período"),
        (r"\bperiodos\b", "períodos"),
        (r"\bPeriodos\b", "Períodos"),
        (r"\bpreco\b", "preço"),
        (r"\bPreco\b", "Preço"),
        (r"\bprecos\b", "preços"),
        (r"\bPrecos\b", "Preços"),
        (r"\bendereco\b", "endereço"),
        (r"\bEndereco\b", "Endereço"),
        (r"\benderecos\b", "endereços"),
        (r"\bEnderecos\b", "Endereços"),
        (r"\bcabecalho\b", "cabeçalho"),
        (r"\bCabecalho\b", "Cabeçalho"),
        (r"\bcobranca\b", "cobrança"),
        (r"\bCobranca\b", "Cobrança"),
        (r"\bcobrancas\b", "cobranças"),
        (r"\bCobrancas\b", "Cobranças"),
        (r"\bseguranca\b", "segurança"),
        (r"\bSeguranca\b", "Segurança"),
        (r"\bpresenca\b", "presença"),
        (r"\bPresenca\b", "Presença"),
        (r"\bopcao\b", "opção"),
        (r"\bOpcao\b", "Opção"),
        (r"\bopcoes\b", "opções"),
        (r"\bOpcoes\b", "Opções"),
        (r"\bpermissao\b", "permissão"),
        (r"\bPermissao\b", "Permissão"),
        (r"\bpermissoes\b", "permissões"),
        (r"\bPermissoes\b", "Permissões"),
        (r"\bsecao\b", "seção"),
        (r"\bSecao\b", "Seção"),
        (r"\bsecoes\b", "seções"),
        (r"\bSecoes\b", "Seções"),
        (r"\bposicao\b", "posição"),
        (r"\bPosicao\b", "Posição"),
        (r"\bposicoes\b", "posições"),
        (r"\bPosicoes\b", "Posições"),
        (r"\bcondicao\b", "condição"),
        (r"\bCondicao\b", "Condição"),
        (r"\bcondicoes\b", "condições"),
        (r"\bCondicoes\b", "Condições"),
        (r"\bsituacao\b", "situação"),
        (r"\bSituacao\b", "Situação"),
        (r"\bsituacoes\b", "situações"),
        (r"\bSituacoes\b", "Situações"),
        (r"\binfracao\b", "infração"),
        (r"\bInfracao\b", "Infração"),
        (r"\binfracoes\b", "infrações"),
        (r"\bInfracoes\b", "Infrações"),
        (r"\borgao\b", "órgão"),
        (r"\bOrgao\b", "Órgão"),
        (r"\borgaos\b", "órgãos"),
        (r"\bOrgaos\b", "Órgãos"),
        (r"\bautuacao\b", "autuação"),
        (r"\bAutuacao\b", "Autuação"),
        (r"\bservico\b", "serviço"),
        (r"\bServico\b", "Serviço"),
        (r"\bservicos\b", "serviços"),
        (r"\bServicos\b", "Serviços"),
        (r"\brelatorio\b", "relatório"),
        (r"\bRelatorio\b", "Relatório"),
        (r"\brelatorios\b", "relatórios"),
        (r"\bRelatorios\b", "Relatórios"),
        (r"\bpromissoria\b", "promissória"),
        (r"\bPromissoria\b", "Promissória"),
        (r"\bpromissorias\b", "promissórias"),
        (r"\bPromissorias\b", "Promissórias"),
        (r"\btraducao\b", "tradução"),
        (r"\bTraducao\b", "Tradução"),
        (r"\btraducoes\b", "traduções"),
        (r"\bTraducoes\b", "Traduções"),
        (r"\bportugues\b", "português"),
        (r"\bPortugues\b", "Português"),
        (r"\bIndicacao\b", "Indicação"),
        (r"\bindicacao\b", "indicação"),
        (r"\bIndicacoes\b", "Indicações"),
        (r"\bindicacoes\b", "indicações"),
        (r"\bPromocao\b", "Promoção"),
        (r"\bpromocao\b", "promoção"),
        (r"\bPromocoes\b", "Promoções"),
        (r"\bpromocoes\b", "promoções"),
        (r"\bLocacao\b", "Locação"),
        (r"\blocacao\b", "locação"),
        (r"\bLocacoes\b", "Locações"),
        (r"\blocacoes\b", "locações"),
        (r"\bContratacao\b", "Contratação"),
        (r"\bcontratacao\b", "contratação"),
        (r"\bMotivacao\b", "Motivação"),
        (r"\bmotivacao\b", "motivação"),
        (r"\bNoticia\b", "Notícia"),
        (r"\bnoticia\b", "notícia"),
        (r"\bNoticias\b", "Notícias"),
        (r"\bnoticias\b", "notícias"),
        (r"\bPais\b", "País"),
        (r"\bpais\b", "país"),
        (r"\bPaises\b", "Países"),
        (r"\bpaises\b", "países"),
        (r"\bpublicacao\b", "publicação"),
        (r"\bPublicacao\b", "Publicação"),
        (r"\bpublicacoes\b", "publicações"),
        (r"\bPublicacoes\b", "Publicações"),
        (r"\bNao\b", "Não"),
        (r"\bnao\b", "não"),
        # grafias comuns que não batem nos sufixos -cao/-coes
        (r"\breconexao\b", "reconexão"),
        (r"\bReconexao\b", "Reconexão"),
        (r"\bexclusao\b", "exclusão"),
        (r"\bExclusao\b", "Exclusão"),
        (r"\bsubstituido\b", "substituído"),
        (r"\bSubstituido\b", "Substituído"),
        (r"\bsubstituida\b", "substituída"),
        (r"\bSubstituida\b", "Substituída"),
        (r"\besta fazendo\b", "está fazendo"),
        (r"\bEsta fazendo\b", "Está fazendo"),
        (r"\bdiaria\b", "diária"),
        (r"\bDiaria\b", "Diária"),
        (r"\bdiarias\b", "diárias"),
        (r"\bDiarias\b", "Diárias"),
        (r"\bSaida\b", "Saída"),
        (r"\bsaida\b", "saída"),
        (r"\bSaidas\b", "Saídas"),
        (r"\bsaidas\b", "saídas"),
        (r"\bcomissao\b", "comissão"),
        (r"\bComissao\b", "Comissão"),
        (r"\bcomissoes\b", "comissões"),
        (r"\bComissoes\b", "Comissões"),
        (r"\bespecifica\b", "específica"),
        (r"\bEspecifica\b", "Específica"),
        (r"\bespecifico\b", "específico"),
        (r"\bEspecifico\b", "Específico"),
        (r"\bespecificas\b", "específicas"),
        (r"\bEspecificas\b", "Específicas"),
        (r"\bespecificos\b", "específicos"),
        (r"\bEspecificos\b", "Específicos"),
        (r"\bbem sucedida\b", "bem-sucedida"),
        (r"\bBem sucedida\b", "Bem-sucedida"),
        (r"\bbem sucedido\b", "bem-sucedido"),
        (r"\bBem sucedido\b", "Bem-sucedido"),
        (r"\bsite publico\b", "site público"),
        (r"\bSite publico\b", "Site público"),
        (r"\bautorenovacao\b", "autorrenovação"),
        (r"\bAutorenovacao\b", "Autorrenovação"),
        (r"\bautorenovacoes\b", "autorrenovações"),
        (r"\bAutorenovacoes\b", "Autorrenovações"),
        (r"\bproximas\b", "próximas"),
        (r"\bProximas\b", "Próximas"),
        (r"\bproximos\b", "próximos"),
        (r"\bProximos\b", "Próximos"),
        (r"\bjá esta\b", "já está"),
        (r"\bja esta\b", "já está"),
        (r"\bJá esta\b", "Já está"),
        (r"\bJa esta\b", "Já está"),
        (r"\bodometro\b", "odômetro"),
        (r"\bOdometro\b", "Odômetro"),
        (r"\bodometros\b", "odômetros"),
        (r"\bOdometros\b", "Odômetros"),
        (r"Devolução\(oes\)", "Devolução(ões)"),
    ]

    for pat, repl in rules:
        s = re.sub(pat, repl, s)

    # Sufixos: \b antes de "cao/coes/..." falha quando a letra anterior também é alfabética
    # (ex.: configuracao, Alteracoes). Exige letra/dígito imediatamente antes do sufixo.
    _p = r"(?<=[0-9A-Za-záéíóúÁÉÍÓÚâêôÂÊÔãõÃÕçÇñÑ])"
    suffix_rules = [
        (r"\bssoes\b", "ssões"),
        (r"\bssao\b", "ssão"),
        (_p + r"icoes\b", "ições"),
        (_p + r"icao\b", "ição"),
        (_p + r"coes\b", "ções"),
        (_p + r"cao\b", "ção"),
        (_p + r"encias\b", "ências"),
        (_p + r"encia\b", "ência"),
        (_p + r"ancias\b", "âncias"),
        (_p + r"ancia\b", "ância"),
        (_p + r"enca\b", "ença"),
    ]
    for pat, repl in suffix_rules:
        s = re.sub(pat, repl, s)

    s = s.replace("não não", "não")
    if locale == "pt_PT":
        s = _pt_pt_postprocess(s)
    return s


def process_file(path: Path, locale: str = "pt_BR") -> bool:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    changed = False
    out: list[str] = []
    for line in lines:
        stripped = line.lstrip()
        if stripped.startswith("//") or stripped.startswith("*") or stripped.startswith("/*"):
            out.append(line)
            continue
        span = extract_string_span(line)
        if span is None:
            out.append(line)
            continue
        a, b = span
        inner = line[a:b]
        new_inner = transform_value(inner, locale=locale)
        if new_inner != inner:
            changed = True
            line = line[:a] + new_inner + line[b:]
        out.append(line)
    if changed:
        path.write_text("".join(out), encoding="utf-8")
    return changed


def main() -> int:
    lang = sys.argv[1] if len(sys.argv) > 1 else _DEFAULT_LANG
    if lang not in ("pt_BR", "pt_PT"):
        print("Uso: fix_pt_br_accents.py [pt_BR|pt_PT]", file=sys.stderr)
        return 2
    lang_path = lang_dir_for(lang)
    if not lang_path.is_dir():
        print(f"Diretório não encontrado: {lang_path}", file=sys.stderr)
        return 1
    n = 0
    for f in sorted(lang_path.rglob("*.php")):
        if process_file(f, locale=lang):
            print(f"Atualizado: {f.relative_to(ROOT)}")
            n += 1
    print(f"Total de arquivos modificados: {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
